#!/usr/bin/env node
/**
 * Turn a validated flow from plan.json into a Playwright spec file.
 *
 *   node generate-spec.mjs <plan.json> <flowId> <output.spec.ts>
 *
 * A flow that matters enough to run on every commit belongs in CI, not in a
 * report. This is the exit ramp: the same steps the audit just executed, as a
 * test you own and maintain yourself.
 *
 * Flow schema: ../skills/qa-audit/references/plan-schema.md
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { pathToFileURL } from 'node:url';

/** Single-quoted JS string literal. */
export const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;

/** A target is a Playwright locator expression if it looks like one, else a CSS selector. */
const loc = (target) =>
  /^(getBy|locator\()/.test(target) ? `page.${target.startsWith('locator(') ? '' : ''}${target}` : `page.locator(${q(target)})`;

/**
 * URL glob to a RegExp literal. Forward slashes must be escaped inside a regex
 * literal, and the pattern is anchored at the end unless it already ends in a
 * wildcard — otherwise "**\/signup" would also match "/signup/extra".
 */
export function globToRegex(glob) {
  const body = String(glob)
    .replace(/[.+^${}()|[\]\\/]/g, '\\$&')
    .replace(/\*+/g, '.*')
    .replace(/\?/g, '.');
  return `/${body}${glob.endsWith('*') ? '' : '$'}/`;
}

/** Interleave the literal parts of a {{run}} template with the runId variable. */
export function runTemplate(value) {
  const parts = String(value).split('{{run}}');
  const tokens = [];
  parts.forEach((part, i) => {
    if (part) tokens.push(q(part));
    if (i < parts.length - 1) tokens.push('runId');
  });
  return tokens.join(' + ') || q('');
}

/** Substitute {{fixture}} placeholders with a reference to the fixtures object. */
export function interpolate(value) {
  if (typeof value !== 'string') return q(value);
  const parts = value.split(/(\{\{\s*[\w.]+\s*\}\})/g).filter(Boolean);
  if (parts.length === 1 && !/^\{\{/.test(parts[0])) return q(value);
  const expr = parts
    .map((p) => (/^\{\{/.test(p) ? `fixtures.${p.replace(/[{}\s]/g, '')}` : q(p)))
    .join(' + ');
  return expr;
}

const ACTIONS = {
  goto: (a) => `await page.goto(${interpolate(a.target)});`,
  click: (a) => `await ${loc(a.target)}.click();`,
  dblclick: (a) => `await ${loc(a.target)}.dblclick();`,
  fill: (a) => `await ${loc(a.target)}.fill(${interpolate(a.value)});`,
  type: (a) => `await ${loc(a.target)}.pressSequentially(${interpolate(a.value)}, { delay: 40 });`,
  press: (a) => (a.target ? `await ${loc(a.target)}.press(${q(a.value)});` : `await page.keyboard.press(${q(a.value)});`),
  select: (a) => `await ${loc(a.target)}.selectOption(${interpolate(a.value)});`,
  check: (a) => `await ${loc(a.target)}.check();`,
  uncheck: (a) => `await ${loc(a.target)}.uncheck();`,
  hover: (a) => `await ${loc(a.target)}.hover();`,
  upload: (a) => `await ${loc(a.target)}.setInputFiles(${interpolate(a.value)});`,
  scroll: (a) => `await page.mouse.wheel(0, ${Number(a.value) || 600});`,
  wait: (a) => `await page.waitForTimeout(${Number(a.value) || 500});`,
};

const EXPECTS = {
  visible: (v) => `await expect(${loc(v)}).toBeVisible();`,
  hidden: (v) => `await expect(${loc(v)}).toBeHidden();`,
  // toHaveURL compares strings exactly; only waitForURL understands globs.
  // Anything with a wildcard becomes a RegExp so the assertion means what it looks like.
  url: (v) => (/[*?]/.test(v) ? `await expect(page).toHaveURL(${globToRegex(v)});` : `await expect(page).toHaveURL(${q(v)});`),
  title: (v) => `await expect(page).toHaveTitle(${q(v)});`,
  text: (v) => `await expect(${loc(v.target ?? v.selector)}).toContainText(${q(v.value ?? v.contains)});`,
  count: (v) => `await expect(${loc(v.target ?? v.selector)}).toHaveCount(${Number(v.value ?? v.count)});`,
  focused: (v) => `await expect(${loc(v)}).toBeFocused();`,
  enabled: (v) => `await expect(${loc(v)}).toBeEnabled();`,
  disabled: (v) => `await expect(${loc(v)}).toBeDisabled();`,
};

export function buildSpec(plan, flow) {
  const L = [];
  const baseURL = plan.serve?.url ?? '';
  const fixtures = { ...(plan.fixtures ?? {}), ...(flow.fixtures ?? {}) };
  const mocks = flow.safety?.mock ?? plan.safety?.mock ?? [];

  L.push(`import { test, expect } from '@playwright/test';`);
  L.push('');
  L.push(`// Generated by qa-audit from .qa-audit/plan.json (flow: ${flow.id}).`);
  L.push(`// Regenerating overwrites this file — copy it out before editing by hand.`);
  L.push('');

  if (Object.keys(fixtures).length) {
    // {{run}} makes a value unique per run — needed for anything the app stores,
    // so a re-run does not collide with the record the previous one created.
    L.push('const runId = String(Date.now());');
    L.push('const fixtures = {');
    for (const [k, v] of Object.entries(fixtures)) {
      L.push(`  ${k}: ${String(v).includes('{{run}}') ? runTemplate(v) : q(v)},`);
    }
    L.push('};');
    L.push('');
  }

  L.push(`test.describe(${q(flow.title ?? flow.id)}, () => {`);

  if (mocks.length) {
    L.push('  test.beforeEach(async ({ page }) => {');
    L.push('    // Side effects are mocked by default — remove to hit the real endpoint.');
    for (const m of mocks) {
      L.push(`    await page.route(${q(m)}, (route) => route.fulfill({ status: 200, body: '{}' }));`);
    }
    L.push('  });');
    L.push('');
  }

  L.push(`  test(${q(flow.title ?? flow.id)}, async ({ page }) => {`);
  if (baseURL) L.push(`    await page.goto(${q(baseURL)});`);

  for (const [i, step] of (flow.steps ?? []).entries()) {
    L.push('');
    L.push(`    // Step ${i + 1} — ${step.name ?? 'unnamed'}`);
    L.push(`    await test.step(${q(step.name ?? `step ${i + 1}`)}, async () => {`);

    // `code` holds the lines playwright-cli emitted while the flow actually ran.
    // Prefer it: targeting by ref produces getByRole locators, which survive a
    // redesign far better than the CSS selectors an `actions` list carries.
    if (step.code?.length) {
      for (const line of step.code) L.push(`      ${String(line).trim()}`);
    } else {
      for (const a of step.actions ?? []) {
        const fn = ACTIONS[a.do];
        L.push(fn ? `      ${fn(a)}` : `      // TODO unsupported action "${a.do}" — write this one by hand`);
      }
    }

    const exp = step.expect ?? {};
    for (const [k, v] of Object.entries(exp)) {
      const fn = EXPECTS[k];
      L.push(fn ? `      ${fn(v)}` : `      // TODO unsupported expectation "${k}"`);
    }
    if (!Object.keys(exp).length) {
      L.push(`      // TODO no expectation declared for this step — add one, or the step proves nothing`);
    }

    L.push('    });');
  }

  L.push('  });');
  L.push('});');
  L.push('');
  return L.join('\n');
}

function main() {
  const [planPath, flowId, output] = process.argv.slice(2);
  if (!planPath || !flowId || !output) {
    console.error('usage: generate-spec.mjs <plan.json> <flowId> <output.spec.ts>');
    process.exit(1);
  }

  let plan;
  try {
    plan = JSON.parse(readFileSync(planPath, 'utf8'));
  } catch (err) {
    console.error(`Cannot read plan "${planPath}": ${err.message}`);
    process.exit(1);
  }

  const flow = (plan.flows ?? []).find((f) => f.id === flowId);
  if (!flow) {
    const known = (plan.flows ?? []).map((f) => f.id).join(', ') || '(none defined)';
    console.error(`No flow "${flowId}" in that plan. Available: ${known}`);
    process.exit(1);
  }

  const spec = buildSpec(plan, flow);
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, spec, 'utf8');

  const steps = (flow.steps ?? []).length;
  const todos = (spec.match(/\/\/ TODO/g) ?? []).length;
  console.log(`OK  ${output}  ·  ${steps} step(s)`);
  if (todos) console.log(`    ${todos} TODO(s) left for you — unsupported actions or missing expectations`);
  console.log(`    run it with:  npx playwright test ${output}`);
}

// Only run when invoked directly, so the module can be imported by tests.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
